### PR TITLE
Fix removed ResourceLocation constructor

### LINKED ISSUE #186: BukkitAudience#openBook doesn't work on Paper 1.21
I've created a simple [test plugin](https://github.com/Syrent/AdventureTest) using these versions of Adventure:
- [adventure-api](https://github.com/Syrent/AdventureTest/blob/master/build.gradle.kts#L25) version 4.17.0
- [adventure-text-minimessage](https://github.com/Syrent/AdventureTest/blob/master/build.gradle.kts#L26) version 4.17.0
- [adventure-platform-bukkit](https://github.com/Syrent/AdventureTest/blob/master/build.gradle.kts#L27) version 4.3.3

I relocated `net.kyori` to `org.sayandev.adventuretest.lib.net.kyori` [as shown here](https://github.com/Syrent/AdventureTest/blob/master/build.gradle.kts#L61) and ran the server using [run-paper version 2.3.0](https://github.com/Syrent/AdventureTest/blob/master/build.gradle.kts#L4) with Paper version 1.21.

However, when I try to [open a book](https://github.com/Syrent/AdventureTest/blob/master/src/main/java/org/sayandev/AdventureTest.java#L27), nothing happens. Everything else, such as the action bar, messages, etc., works as expected.

### PR DESCRIPTION
**Pull request by 56738**
Attempt to use a static factory method if the `ResourceLocation` constructor is not public.

Fixes #186

### CODE REVIEW

File: platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitAccess.java [hunk 1]
```diff
@@ -85,12 +85,20 @@ final class CraftBukkitAccess {
     findMcClassName("core.IRegistryWritable"),
     findMcClassName("core.WritableRegistry")
   );
+  static final @Nullable MethodHandle NEW_RESOURCE_LOCATION;
+
+  static {
+    MethodHandle newResourceLocation = findConstructor(CLASS_RESOURCE_LOCATION, String.class, String.class);
+    if (newResourceLocation == null) {
+      newResourceLocation = searchMethod(CLASS_RESOURCE_LOCATION, Modifier.PUBLIC | Modifier.STATIC, "fromNamespaceAndPath", CLASS_RESOURCE_LOCATION, String.class, String.class);
```
Comment (zml2008) [inline platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitAccess.java:93]: do we need to care about reobf here?

Comment (56738) [reply platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitAccess.java:93]: there are 2 methods with a matching signature, the only difference is error handling (one throws, the other returns null), so the name doesn't matter - tested on mojmap paper 1.21 and reobf spigot 1.21

**Review by zml2008 — APPROVED** [review]
